### ISSUE TITLE
librsync 2.3.1 fails to build under Windows no suitable type found TEST_BIG_ENDIAN

### ISSUE THREAD

**Issue by ericzolf** [librsync/librsync#207] opened 2020-05-31 09:04 UTC
Building librsync 2.3.1 fails under Windows 10 where it used to work with librsync 2.2.1:

```
vagrant@WIN-2JV1T18KDCU C:\Users\vagrant\Develop\librsync-2.3.1>"C:\Program Files\CMake\bin\cmake.exe" -G "Visual Studio 15 2017" -A x64 -D BUILD_RDIFF=OFF . -D CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -D BUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=C:/Users/vagrant/Develop/librsync.d
-- The C compiler identification is MSVC 19.16.27039.0 
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27
023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27
023/bin/Hostx86/x64/cl.exe - works
-- Detecting C compiler ABI info 
-- Detecting C compiler ABI info - done 
-- Detecting C compile features 
-- Detecting C compile features - done
-- DO_RS_TRACE=0 
-- Looking for include file sys/file.h 
-- Looking for include file sys/file.h - not found 
-- Looking for include file sys/stat.h 
-- Looking for include file sys/stat.h - found 
-- Looking for include file sys/types.h 
-- Looking for include file sys/types.h - found 
-- Looking for include file unistd.h 
-- Looking for include file unistd.h - not found 
-- Looking for include file fcntl.h 
-- Looking for include file fcntl.h - found 
-- Looking for include file mcheck.h 
-- Looking for include file mcheck.h - not found 
-- Looking for include file zlib.h 
-- Looking for include file zlib.h - not found 
-- Looking for include file bzlib.h 
-- Looking for include file bzlib.h - not found 
-- Looking for __func__ 
-- Looking for __func__ - found
-- Looking for __FUNCTION__
-- Looking for __FUNCTION__ - found
-- Looking for fseeko
-- Looking for fseeko - not found
-- Looking for fseeko64
-- Looking for fseeko64 - not found
-- Looking for _fseeki64
-- Looking for _fseeki64 - found
-- Looking for fstat64
-- Looking for fstat64 - not found
-- Looking for _fstati64
-- Looking for _fstati64 - found
-- Looking for fileno
-- Looking for fileno - found
-- Looking for _fileno
-- Looking for _fileno - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long
-- Check size of long - done
-- Check size of long long
-- Check size of long long - done
-- Check size of off_t
-- Check size of off_t - done
-- Check size of off64_t
-- Check size of off64_t - failed
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned int
-- Check size of unsigned int - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Compiling to Win32 - printf "%zu" size_t formatting support disabled
-- Check if the system is big endian
-- Searching 16 bit integer
-- Check size of unsigned short
-- Check size of unsigned short - failed
-- Check size of unsigned int
-- Check size of unsigned int - failed
-- Check size of unsigned long
-- Check size of unsigned long - failed
CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/TestBigEndian.cmake:50 (message):
  no suitable type found
Call Stack (most recent call first):
  CMakeLists.txt:115 (TEST_BIG_ENDIAN)


-- Configuring incomplete, errors occurred!
See also "C:/Users/vagrant/Develop/librsync-2.3.1/CMakeFiles/CMakeOutput.log".
See also "C:/Users/vagrant/Develop/librsync-2.3.1/CMakeFiles/CMakeError.log".
```
whereas on the exact same Windows with exactly the same command, it works with librsync 2.2.1:

```
vagrant@WIN-2JV1T18KDCU C:\Users\vagrant\Develop\librsync-2.2.1>"C:\Program Files\CMake\bin\cmake.exe" -G "Visual Stud
io 15 2017" -A x64 -D BUILD_RDIFF=OFF . -D CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -D BUILD_SHARED_LIBS=TRUE -DCMAKE_INS
TALL_PREFIX=C:/Users/vagrant/Develop/librsync.d
-- The C compiler identification is MSVC 19.16.27039.0 
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27
023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27
023/bin/Hostx86/x64/cl.exe - works
-- Detecting C compiler ABI info 
-- Detecting C compiler ABI info - done 
-- Detecting C compile features 
-- Detecting C compile features - done
-- DO_RS_TRACE=0 
-- Looking for include file alloca.h
-- Looking for include file alloca.h - not found 
-- Looking for include file dlfcn.h 
-- Looking for include file dlfcn.h - not found 
-- Looking for include file inttypes.h 
-- Looking for include file inttypes.h - found 
-- Looking for include file memory.h 
-- Looking for include file memory.h - found 
-- Looking for include file stdint.h 
-- Looking for include file stdint.h - found 
-- Looking for include file stdlib.h 
-- Looking for include file stdlib.h - found 
-- Looking for include file strings.h 
-- Looking for include file strings.h - not found 
-- Looking for include file string.h 
-- Looking for include file string.h - found 
-- Looking for include file sys/stat.h 
-- Looking for include file sys/stat.h - found 
-- Looking for include file sys/types.h 
-- Looking for include file sys/types.h - found 
-- Looking for include file unistd.h 
-- Looking for include file unistd.h - not found 
-- Looking for include file bzlib.h 
-- Looking for include file bzlib.h - not found 
-- Looking for include file fcntl.h 
-- Looking for include file fcntl.h - found 
-- Looking for include file malloc.h 
-- Looking for include file malloc.h - found 
-- Looking for include file mcheck.h 
-- Looking for include file mcheck.h - not found 
-- Looking for include file sys/file.h 
-- Looking for include file sys/file.h - not found 
-- Looking for include file zlib.h 
-- Looking for include file zlib.h - not found 
-- Looking for alloca 
-- Looking for alloca - not found 
-- Looking for fseeko 
-- Looking for fseeko - not found 
-- Looking for fseeko64 
-- Looking for fseeko64 - not found 
-- Looking for _fseeki64 
-- Looking for _fseeki64 - found 
-- Looking for fstat64 
-- Looking for fstat64 - not found 
-- Looking for _fstati64 
-- Looking for _fstati64 - found 
-- Looking for fileno 
-- Looking for fileno - found 
-- Looking for _fileno 
-- Looking for _fileno - found 
-- Looking for memmove 
-- Looking for memmove - found 
-- Looking for memset 
-- Looking for memset - found
-- Looking for strchr
-- Looking for strchr - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long
-- Check size of long - done
-- Check size of long long
-- Check size of long long - done
-- Check size of off_t
-- Check size of off_t - done
-- Check size of off64_t
-- Check size of off64_t - failed
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned int
-- Check size of unsigned int - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Compiling to Win32 - printf "%zu" size_t formatting support disabled
-- Check if the system is big endian
-- Searching 16 bit integer
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Searching 16 bit integer - Using unsigned short
-- Check if the system is big endian - little endian
-- System is little-endian.
-- PROJECT_NAME  = librsync
-- BUILD_HOSTNAME = WIN-2JV1T18KDCU
-- CMAKE_SYSTEM = Windows-10.0.17763
-- Could NOT find POPT (missing: POPT_LIBRARIES POPT_INCLUDE_DIRS)
-- Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (messag
e):
  The package name passed to `find_package_handle_standard_args` (LIBB2) does
  not match the name of the calling package (libb2).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Findlibb2.cmake:12 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:191 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find LIBB2 (missing: LIBB2_LIBRARIES LIBB2_INCLUDE_DIRS)
-- Using included blake2 implementation.
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- CMAKE_C_FLAGS  = /DWIN32 /D_WINDOWS /W3
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/vagrant/Develop/librsync-2.2.1
```

I attach the log files for both runs:
[CMakeError_221.log](https://github.com/librsync/librsync/files/4707382/CMakeError_221.log)
[CMakeError_231.log](https://github.com/librsync/librsync/files/4707383/CMakeError_231.log)
[CMakeOutput_221.log](https://github.com/librsync/librsync/files/4707384/CMakeOutput_221.log)
[CMakeOutput_231.log](https://github.com/librsync/librsync/files/4707385/CMakeOutput_231.log)

The results are consistent within [Travis CI](https://travis-ci.com/github/rdiff-backup/rdiff-backup/jobs/341863128) and in my Vagrant/Ansible generated VM: https://github.com/rdiff-backup/rdiff-backup/commit/a28f5212491d5c8356ff7bb4d5a4fcd5c33a0ee9 (Travis got a new Python version but it is unrelated, the VM was already on 3.7.7).

Any help is much appreciated.

**Comment by dbaarda** [comment] 2020-05-31 09:50
Ugh... Windows again :-(

At first glance it looks like this is a problem inside CMake's own Test_Big_Endian support, which would be weird.

Looking closer, it looks like its actually caused by an unrecognised  `-wno-format` compiler argument added by our `%zu` size_t formatting check that tries to shut up spurious warnings for windows using mingw.

That particular piece of our cmake has been an endless source of pain. It feels like any attempt to fix some combination of compiler, compiler platform, and target platform with "Windows" anywhere in the mix will break some other combination.

I welcome anyone's attempts to make this better. I'll try and figure out something that works later, but I don't have easy access to a platform for testing it.

**Comment by ericzolf** [comment] 2020-05-31 10:12
Your reaction could have come from me :smiley:  I have the same problem as you, check my Vagrant/Playbook setup, it works well for me even if I need to destroy and re-create my environment each 90 days (`vagrant ssh` even works, Bash and cygwin are installed, it almost feels like at home aka Linux, as long as I don't need a UI). Just copy the windows directory at https://github.com/rdiff-backup/rdiff-backup/tree/ericzolf-upgrade-py-win-387_/tools/windows and call `vagrant up` (assuming you have the right pre-requisites installed, which I tried to document in the readme) and you can develop librsync under Windows (see the corresponding playbook on how to build). Don't hesitate to ask questions if you decide to go this route and need help.

**Comment by dbaarda** [comment] 2020-06-04 12:56
Well... that turned into quite the Yak-shaving exercise. See #208 for my fix, which turned into something which exposed and fixed a bunch of slightly dodgy things in the code. I'm about to submit this soon, but I'd welcome any input/suggestions.

I've setup a Travis Windows build check which is working. Unfortunately I couldn't find a libpopt that I could pull in using chocolatey which is what Travis supports. This means it can't build/test rdiff, only the library and supporting unittests.  You can see a sample run here;

https://travis-ci.org/github/librsync/librsync/jobs/694617640

The Travis documentation for their Windows build environment says mingw is installed. It also talks about installing MSYS2 which I believe is the new Cygwin. It might be that libpopt is available or included with those alternatives. I haven't even started figuring how/if it's worth adding builds that use these;

https://docs.travis-ci.com/user/reference/windows/

I dug around and it seems like popt has kinda atrophied in popularity. I wonder if switching to a GNU's gengetopt would be a good idea. I believe that gengetopt is available via chocolatey in a GnuWin package.

@ericzolf Are you managing to compile rdiff with MSVC? What are you doing for popt?

**Comment by dbaarda** [comment] 2020-06-04 13:04
I just merged #208 so this is fixed. However I'm still interested in any followup comments/suggestions if anyone has any.

**Closed by dbaarda** 2020-06-04 13:04 UTC

**Comment by ericzolf** [comment] 2020-06-04 13:07
I'll check the fix asap and give you feedback. Thanks for the fast answer.

> @ericzolf Are you managing to compile rdiff with MSVC? What are you doing for popt?

No, we explicitly skip the compilation of rdiff. I didn't write the initial build steps but lack of popt might be the reason.

**Comment by dbaarda** [comment] 2020-06-04 13:28
Thanks for checking this. Feel free to reopen this if there are still problems... I probably closed this a bit too soon.

**Comment by ericzolf** [comment] 2020-06-06 10:57
No need to re-open, looks good to me. Looking forward the release of version 2.3.2 :sweat_smile:
