### ISSUE TITLE
rdiff v2.3.4 I/O error on Linux Mint

### ISSUE THREAD

**Issue by mariomadproductions** [librsync/librsync#252] opened 2023-02-20 20:28 UTC
OS: Linux Mint 20.3

```
librsync: ERROR: (rs_infilebuf_fill) no error bit, but got 0 return when trying to read
rdiff: Failed, IO error.
```
I get this when I try and generate a signature file using rdiff from v2.3.4 built from source. All the tests passed running `make check`.

**Comment by dbaarda** [comment] 2023-02-22 01:06
Ugh... can you give a detailed cmdline example, sample input files, and error output so I can try to reproduce this?

I can't seem to find anywhere in the code that would produce an error message like this. Are you sure it's not with some mangled patch applied?

**Comment by mariomadproductions** [comment] 2023-02-22 18:16
It seems like its because I was following the (apparently outdated) [build instructions](https://librsync.github.io/page_install.html). When I followed [check.yml](https://github.com/librsync/librsync/blob/master/.github/workflows/check.yml), it works.

**Comment by dbaarda** [comment] 2023-02-23 03:33
The build instructions in the doc are not that different from the check.yml and should work.

In particular the error message you got is very weird and looks like an error message from an old/miss-matched version. It's not something I can see the current version ever emitting. So maybe it was a dirty checkout or it dynamically linked with an older librsync library?

**Comment by mariomadproductions** [comment] 2023-02-23 11:45
Hm yeah, that could have been it, as I did have the repo librysnc installed at some point. I may have forgot to uninstall it before installing v2.3.4.

**Comment by dbaarda** [comment] 2023-02-24 05:41
I'm going to close this as resolved. Feel free to reopen it if you have further related discoveries or problems.

**Closed by dbaarda** 2023-02-24 05:41 UTC

**Comment by mariomadproductions** [comment] 2023-02-24 14:18
Yeah probably should be closed. Thanks.
