### ISSUE TITLE
excess cpu use in rs_mdfour / rs_search_for_block / rs_findmatch

### ISSUE THREAD

**Issue by vps2fast** [librsync/librsync#11] opened 2014-09-30 10:48 UTC
Hello!

I'm using rdiff for creating incremental backups and it hangs every day with one file with 5GB in size.

OS: CentOS 6

``` bash
ps aux|grep rdiff
root      771334  0.0  0.0 103248   892 pts/0    S+   14:39   0:00 grep rdiff
root      945509 99.2  0.0  78444 59484 ?        R    Sep29 1207:21 rdiff --block-size=1048576 --input-size=16777216 --output-size=16777216 delta /vz/tmp/extracted_backup_34bdf94b-43eb-4491-bc65-196d8f624d48.signature /vz/private/4822/root.hdd/root.hdd /vz/tmp/extracted_backup_34bdf94b-43eb-4491-bc65-196d8f624d48.signature.delta
```

Source files:

```
ls -al /vz/tmp/extracted_backup_34bdf94b-43eb-4491-bc65-196d8f624d48.signature.delta
-rw-r--r-- 1 root root 191889408 Sep 30 13:41 /vz/tmp/extracted_backup_34bdf94b-43eb-4491-bc65-196d8f624d48.signature.delta

ls -alh /vz/tmp/extracted_backup_34bdf94b-43eb-4491-bc65-196d8f624d48.signature.delta
-rw-r--r-- 1 root root 183M Sep 30 13:41 /vz/tmp/extracted_backup_34bdf94b-43eb-4491-bc65-196d8f624d48.signature.delta

ls -la /vz/tmp/extracted_backup_34bdf94b-43eb-4491-bc65-196d8f624d48.signature
-rw-r--r-- 1 root root 49752 Sep 29 18:23 /vz/tmp/extracted_backup_34bdf94b-43eb-4491-bc65-196d8f624d48.signature
```

Strace show nothing:

``` bash
strace -f -p 945509
Process 945509 attached - interrupt to quit
```

But gdb show so much very interesting info:

```
debuginfo-install librsync-0.9.7-15.el6.x86_64
```

``` bash
(gdb) bt
#0  0x00007f2d96a53bbf in rs_mdfour64 (m=0x7fff58b760a0, p=0x7f2d946d33a4) at mdfour.c:113
#1  0x00007f2d96a5413f in rs_mdfour_block (md=0x7fff58b760a0, in_void=<value optimized out>, n=<value optimized out>) at mdfour.c:263
#2  rs_mdfour_update (md=0x7fff58b760a0, in_void=<value optimized out>, n=<value optimized out>) at mdfour.c:359
#3  0x00007f2d96a5442a in rs_mdfour (out=0x7fff58b76170 "\251\017\226/\035B\253\212\311lH<\222\222t\230", in=0x7f2d946c63a4, n=1048576) at mdfour.c:389
#4  0x00007f2d96a55bbc in rs_search_for_block (weak_sum=0, inbuf=<value optimized out>, block_len=<value optimized out>, sig=0xb3dd80, stats=<value optimized out>, match_where=<value optimized out>)
    at search.c:143
#5  0x00007f2d96a52b01 in rs_findmatch (job=0xb3dbd0) at delta.c:272
#6  rs_delta_s_scan (job=0xb3dbd0) at delta.c:156
#7  0x00007f2d96a5391e in rs_job_work (job=0xb3dbd0, buffers=0x7fff58b762e0) at job.c:187
#8  rs_job_iter (job=0xb3dbd0, buffers=0x7fff58b762e0) at job.c:145
#9  0x00007f2d96a53a39 in rs_job_drive (job=0xb3dbd0, buf=0x7fff58b762e0, in_cb=0x7f2d96a51ee0 <rs_infilebuf_fill>, in_opaque=<value optimized out>, out_cb=0x7f2d96a51d90 <rs_outfilebuf_drain>, 
    out_opaque=<value optimized out>) at job.c:241
#10 0x00007f2d96a56b72 in rs_whole_run (job=0xb3dbd0, in_file=<value optimized out>, out_file=0xb3d990) at whole.c:80
#11 0x00007f2d96a56cf7 in rs_delta_file (sig=<value optimized out>, new_file=0xb3d750, delta_file=0xb3d990, stats=0x7fff58b76380) at whole.c:154
#12 0x000000000040149b in rdiff_delta (argc=-1804782684, argv=0xb208f4c2) at rdiff.c:298
#13 rdiff_action (argc=-1804782684, argv=0xb208f4c2) at rdiff.c:358
#14 main (argc=-1804782684, argv=0xb208f4c2) at rdiff.c:374
```

With disk system everything looks fine:

``` bash
cat  /vz/tmp/extracted_backup_34bdf94b-43eb-4491-bc65-196d8f624d48.signature |pv >/dev/null
48.6kB 0:00:00 [ 452MB/s] [   <=>                  
cat /vz/private/4822/root.hdd/root.hdd  |pv >/dev/null
4.05GB 0:00:02 [1.36GB/s] [          <=>                  
```

Please help me :(

**Comment by cgm999** [comment] 2015-05-06 18:50
I think the issue is due SRC missing 1 continous block of zeros(1MB in this case), but DST having quite a big area (which is common for VM disk image), and some other block that have the weak sum same with the one of 1MB of \x00 . rdiff would keep doing STRONG_SUM for 1MB(when the large area of \0xx is hit) ,while moving the window 1 byte ,which is sloow (on my CPU is no moving the window with 1000bytes every few seconds)

Using the default block size of 2KB should not hit this issue due 2 reasons: STRONG_SUM(2KB) is way more fast and also the chance of a not having 2KB \0xx is lower.

vps2fast => if you still have the data that triggers this , try to create a new SRC = ORIG_SRC + 1MB of \x00 (begin or end of the file) then rerun rdiff.  Also try running rdiff with ORIG_SRC and a default block size (-b 2048).

One possible fix that I see is to detect areas of zero (when SRC is missing it) and issue literal commands to delta output . I have some initial work done , if there is interest I can try get it completed :)

**Comment by pavel-odintsov** [comment] 2015-05-06 19:36
I'm vpss2fast. I fixed this issue by complete rdiff rewrite in C++ with disabled rolling checksumms.

**Comment by cgm999** [comment] 2015-05-07 05:36
Hi pavel, it would be good if the issue you encounter is the one from my theory, so if you can try to test as suggessted .

**Comment by pavel-odintsov** [comment] 2015-05-07 07:53
Unfortunately, I can't because my tool is incompatible with rdiff anymore :(

**Comment by cgm999** [comment] 2015-05-07 07:56
Well there is the rdiff from librsync :). That means generating a signature with it and then delta, if you still have the data from when this issue started.

**Comment by dbaarda** [comment] 2017-03-01 03:37
Looking at this again, I think the problem was collisions for a weaksum of 0. In particular, there was long runs of zeros which the rolling checksum gave a zero weaksum for at every byte offset. The signature must have had one non-zero block with a zero weaksum and no all-zero's blocks.

A contributing factor here is the blocksize of 1M. The rollsum we use for the weaksum has s0=sum(inbytes+31),s1=sum(s0), with both s0 and s1 truncated to 16 bits and then appended together. The +31 added to each byte is to ensure that the block length ends up encoded in the sum so eg blocks of zeros of different sizes don't end up with the same sum. When the blocksize is 1M, the +31 just cleanly overflows out of both s0 and s1, so it reduces to s0=sum(inbytes),s1=sum(s0), which gives you zero for a 1Mblock of zero's. This happens for any blocksize that is a power of 2 greater than 2^16.

I suspect if you had chosen a blocksize of 1M-1 the problem would have gone away.

Note the recommended blocksize is sqrt(filesize), so a 1M blocksize is pretty large.

**Comment by dbaarda** [comment] 2017-06-02 01:57
Performance issues for large files have been improved with the new hashtable. I think the best fix for the remaining points is to use a better rolling hash. That is being tracked in #3, so I'm going to close this as a duplicate of that.

**Closed by dbaarda** 2017-06-02 01:57 UTC
Labels: performance
